import type { Config } from "tailwindcss";
import { nextui } from "@nextui-org/react";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        blue: {
          0: 'var(--blue-0)',
          1: 'var(--blue-1)',
          2: 'var(--blue-2)',
          3: 'var(--blue-3)',
          4: 'var(--blue-4)',
          5: 'var(--blue-5)',
          6: 'var(--blue-6)',
          7: 'var(--blue-7)',
          8: 'var(--blue-8)',
          9: 'var(--blue-9)',
        },
        purple: {
          0: 'var(--purple-0)',
          1: 'var(--purple-1)',
          2: 'var(--purple-2)',
          3: 'var(--purple-3)',
          4: 'var(--purple-4)',
          5: 'var(--purple-5)',
          6: 'var(--purple-6)',
          7: 'var(--purple-7)',
          8: 'var(--purple-8)',
          9: 'var(--purple-9)',
        },
        red: {
          0: 'var(--red-0)',
          1: 'var(--red-1)',
          2: 'var(--red-2)',
          3: 'var(--red-3)',
          4: 'var(--red-4)',
          5: 'var(--red-5)',
          6: 'var(--red-6)',
          7: 'var(--red-7)',
          8: 'var(--red-8)',
          9: 'var(--red-9)',
        },
        green: {
          0: 'var(--green-0)',
          1: 'var(--green-1)',
          2: 'var(--green-2)',
          3: 'var(--green-3)',
          4: 'var(--green-4)',
          5: 'var(--green-5)',
          6: 'var(--green-6)',
          7: 'var(--green-7)',
          8: 'var(--green-8)',
          9: 'var(--green-9)',
        },
        yellow: {
          0: 'var(--yellow-0)',
          1: 'var(--yellow-1)',
          2: 'var(--yellow-2)',
          3: 'var(--yellow-3)',
          4: 'var(--yellow-4)',
          5: 'var(--yellow-5)',
          6: 'var(--yellow-6)',
          7: 'var(--yellow-7)',
          8: 'var(--yellow-8)',
          9: 'var(--yellow-9)',
        },
        grey: {
          0: 'var(--grey-0)',
          1: 'var(--grey-1)',
          2: 'var(--grey-2)',
          3: 'var(--grey-3)',
          4: 'var(--grey-4)',
          5: 'var(--grey-5)',
          6: 'var(--grey-6)',
          7: 'var(--grey-7)',
          8: 'var(--grey-8)',
          9: 'var(--grey-9)',
        },
      },
      fontFamily: {
        exo: ['Exo', 'sans-serif'],
      },
    },
  },
  darkMode: "class",
  plugins: [nextui()],
} satisfies Config;
