import type { Metadata } from "next";
import "./globals.css";

import { Exo } from 'next/font/google';

import { Providers } from './providers';
import '@coinbase/onchainkit/styles.css';
import { cookieToInitialState } from 'wagmi';
import { getConfig } from './wagmi';
import { headers } from 'next/headers';

const exo = Exo({
  subsets: ['latin'], // Specify character subset
  weight: ['400', '700'], // Add desired font weights
  variable: '--font-exo', // Optional: Define a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    getConfig(),
    (await headers()).get('cookie')
  );

  return (
    <html lang="en">
      <body className={`${exo.variable}`}>
        <Providers initialState={initialState}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
