import type { Metadata } from "next";
import "./globals.css";

import { Exo } from 'next/font/google';

const exo = Exo({
  subsets: ['latin'], // Specify character subset
  weight: ['400', '700'], // Add desired font weights
  variable: '--font-exo', // Optional: Define a CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exo.variable}`}>

        {children}
      </body>
    </html>
  );
}
